### PR TITLE
Persistent subscription: ACK issue

### PR DESCRIPTION
**Pull request by lzukowski**
…mers

### CODE REVIEW

**Comment by johnbywater** [comment]
Please would it be possible to grant me write access to your repo, so I can push changes (specifically to merge in the latest changes to pin Poetry version to 1.5.1)?

**Comment by johnbywater** [comment]
Continuing the discussion in #8, there was a bug. For performance reasons, N/ACKs are sent to the server in batches and buffered in the client. However, in the scenario you expressed, the N/ACKs weren't being sent before the subscription exited, and so those N/ACKs weren't being sent at all. Hence subsequent consumers received events again. I've adjusted the code so that all remaining buffered N/ACKs are sent to the server when the subscription is stopped. The nice test you wrote now passes.

Many thanks for raising this issue. I'm sorry for the delay in responding, which was due to an extended summer break (cycling in Europe).

**Comment by lzukowski** [comment]
Thx for fixing it!

**Comment by johnbywater** [comment]
You're welcome! These changes have just been published as version 0.18 (and 1.0b3):
https://pypi.org/project/esdbclient/0.18/
https://pypi.org/project/esdbclient/1.0b3/

**Pull request merged**
